project:
  type: website
  output-dir: docs

website:
  title: "chiralcarbon"
  navbar:
    logo: notes/src/img/chiralCarbon.png
    left:
      - href: index.qmd
        text: Home
      - notebooks.qmd
  sidebar: 
    style: floating
    contents: 
      - section: "Physical chemistry"
        contents: 
          - notes/physichem/chemical_kinetics.qmd
          - notes/physichem/electrolyte_solutions.qmd
          - notes/meta_chiral/howisdone.qmd
      - section: "Novel Materials"
        contents: 
          - notes/development_of_materials/nanowires.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    html-math-method: katex
    header-includes: <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/mhchem.min.js" integrity="sha384-RTN08a0AXIioPBcVosEqPUfKK+rPp+h1x/izR7xMkdMyuwkcZCWdxO+RSwIFtJXN"  crossorigin="anonymous"></script>



